version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn compile
      - run:
          name: Build Server
          command: mvn compile -pl server
      - run:
          name: Build Client
          command: mvn compile -pl client
      - run:
          name: Test
          command: mvn test
      - run:
          name: Test Server
          command: mvn test -pl server
      - run:
          name: Test Client
          command: mvn test -pl client

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          parallelism: 3
